use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone)]
pub struct Project {
    pub name: String,
    pub path: PathBuf,
    pub host: String, // github, gitlab, gitea, none
    pub org: String,
    pub repo: String,
    pub url: String,
    pub branch: String,
    pub status: String, // active, archived, stale, local-only
    pub lang: Vec<String>,
}

/// Scan ~/문서/프로젝트/ and return all projects
pub fn scan() -> Vec<Project> {
    let home = std::env::var("HOME").unwrap_or_default();
    let proj_dir = PathBuf::from(&home).join("문서/프로젝트");

    if !proj_dir.is_dir() {
        return Vec::new();
    }

    let mut projects = Vec::new();

    if let Ok(entries) = fs::read_dir(&proj_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();

            let remote = git_remote(&path);
            let branch = git_branch(&path);
            let lang = detect_lang(&path);
            let (host, org, repo, url, status) = parse_remote(&remote);

            projects.push(Project {
                name,
                path,
                host,
                org,
                repo,
                url,
                branch,
                status,
                lang,
            });
        }
    }

    projects.sort_by(|a, b| a.name.cmp(&b.name));
    projects
}

/// Generate NCL output for projects
pub fn sync_ncl() {
    let home = std::env::var("HOME").unwrap_or_default();
    let ncl_path = find_ncl_path(&home);
    let projects = scan();

    let mut output = String::new();
    output.push_str("# Auto-generated by mai run git project sync\n\n");
    output.push_str("{\n");

    for section in &["github", "gitlab", "gitea", "none"] {
        let filtered: Vec<&Project> = projects.iter().filter(|p| p.host == *section).collect();
        if filtered.is_empty() {
            continue;
        }

        let label = if *section == "none" { "local" } else { section };
        output.push_str(&format!("  {} = {{\n", label));

        for p in &filtered {
            output.push_str(&format!("    \"{}\" = {{\n", p.name));
            output.push_str(&format!("      name = \"{}\",\n", p.name));
            output.push_str(&format!("      path = \"~/문서/프로젝트/{}\",\n", p.name));
            output.push_str(&format!(
                "      host = '{}',\n",
                if p.host == "none" { "none" } else { &p.host }
            ));
            if !p.org.is_empty() {
                output.push_str(&format!("      org = \"{}\",\n", p.org));
            }
            if !p.repo.is_empty() {
                output.push_str(&format!("      repo = \"{}\",\n", p.repo));
            }
            if !p.url.is_empty() {
                output.push_str(&format!("      url = \"{}\",\n", p.url));
            }
            output.push_str(&format!("      branch = \"{}\",\n", p.branch));
            output.push_str(&format!("      status = '{}',\n", p.status));
            if !p.lang.is_empty() {
                let langs: Vec<String> = p.lang.iter().map(|l| format!("\"{}\"", l)).collect();
                output.push_str(&format!("      lang = [{}],\n", langs.join(", ")));
            }
            output.push_str("    },\n");
        }
        output.push_str("  },\n\n");
    }

    output.push_str("}\n");

    if let Err(e) = fs::write(&ncl_path, &output) {
        eprintln!("[projects] NCL 쓰기 실패: {}", e);
        return;
    }

    let counts: std::collections::HashMap<&str, usize> =
        projects
            .iter()
            .fold(std::collections::HashMap::new(), |mut acc, p| {
                *acc.entry(p.host.as_str()).or_default() += 1;
                acc
            });

    println!(
        "[projects-sync] {} 갱신 ({}개 프로젝트: github={}, gitlab={}, gitea={}, local={})",
        ncl_path.display(),
        projects.len(),
        counts.get("github").unwrap_or(&0),
        counts.get("gitlab").unwrap_or(&0),
        counts.get("gitea").unwrap_or(&0),
        counts.get("none").unwrap_or(&0),
    );
}

/// Print project list
pub fn status() {
    let projects = scan();
    println!("=== 프로젝트 ({}) ===\n", projects.len());

    let mut current_host = String::new();
    for p in &projects {
        if p.host != current_host {
            current_host = p.host.clone();
            let label = match current_host.as_str() {
                "github" => "GitHub",
                "gitlab" => "GitLab",
                "gitea" => "Gitea",
                _ => "Local",
            };
            println!("[{}]", label);
        }
        let lang_str = if p.lang.is_empty() {
            String::new()
        } else {
            format!(" ({})", p.lang.join(", "))
        };
        println!("  {:<30} {:<8} {}{}", p.name, p.branch, p.status, lang_str);
    }
}

// === Helpers ===

fn git_remote(path: &Path) -> String {
    Command::new("git")
        .args(["-C", &path.to_string_lossy(), "remote", "get-url", "origin"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}

fn git_branch(path: &Path) -> String {
    Command::new("git")
        .args(["-C", &path.to_string_lossy(), "branch", "--show-current"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "main".to_string())
}

fn detect_lang(path: &Path) -> Vec<String> {
    let mut langs = Vec::new();
    if path.join("Cargo.toml").exists() {
        langs.push("rust".to_string());
    }
    if path.join("go.mod").exists() {
        langs.push("go".to_string());
    }
    if path.join("package.json").exists() {
        langs.push("typescript".to_string());
    }
    if path.join("composer.json").exists() {
        langs.push("php".to_string());
    }
    if path.join("pyproject.toml").exists() || path.join("setup.py").exists() {
        langs.push("python".to_string());
    }
    langs
}

fn parse_remote(remote: &str) -> (String, String, String, String, String) {
    if remote.is_empty() {
        return (
            "none".into(),
            String::new(),
            String::new(),
            String::new(),
            "local-only".into(),
        );
    }

    if remote.contains("github.com") {
        let stripped = remote
            .replace("https://github.com/", "")
            .replace("git@github.com:", "")
            .replace(".git", "");
        let parts: Vec<&str> = stripped.splitn(2, '/').collect();
        let org = parts.first().unwrap_or(&"").to_string();
        let repo = parts.get(1).unwrap_or(&"").to_string();
        let url = format!("https://github.com/{}/{}", org, repo);
        return ("github".into(), org, repo, url, "active".into());
    }

    if remote.contains("gitlab") || remote.contains("10.50") {
        let url = remote.replace("oauth2:", "").to_string();
        let parts: Vec<&str> = url.rsplitn(3, '/').collect();
        let repo = parts.first().unwrap_or(&"").replace(".git", "");
        let org = parts.get(1).unwrap_or(&"").to_string();
        return ("gitlab".into(), org, repo, url, "active".into());
    }

    if remote.contains("gitea") || remote.contains("gupsa") || remote.contains("eunha") {
        let url = remote.replace("oauth2:", "").to_string();
        let parts: Vec<&str> = url.rsplitn(3, '/').collect();
        let repo = parts.first().unwrap_or(&"").replace(".git", "");
        let org = parts.get(1).unwrap_or(&"").to_string();
        return ("gitea".into(), org, repo, url, "active".into());
    }

    (
        "none".into(),
        String::new(),
        String::new(),
        remote.to_string(),
        "active".into(),
    )
}

fn find_ncl_path(home: &str) -> PathBuf {
    // Look for ncl/ in known project locations
    let candidates = [
        PathBuf::from(home).join("문서/프로젝트/mac-app-init/ncl/projects.ncl"),
        PathBuf::from(home).join("Documents/Claude/mac-app-init/ncl/projects.ncl"),
    ];
    for c in &candidates {
        if c.parent().map(|p| p.is_dir()).unwrap_or(false) {
            return c.clone();
        }
    }
    // Fallback
    PathBuf::from(home).join("문서/프로젝트/mac-app-init/ncl/projects.ncl")
}
