pub mod common;
pub mod config;
pub mod constants;
pub mod models;

#[cfg(domain = "cron")]
pub mod cron;
#[cfg(domain = "defaults")]
pub mod defaults;
#[cfg(domain = "dotfiles")]
pub mod dotfiles;
#[cfg(domain = "files")]
pub mod files;
#[cfg(domain = "github")]
pub mod github;
#[cfg(domain = "init")]
pub mod init;
#[cfg(domain = "keyboard")]
pub mod keyboard;
#[cfg(domain = "mount")]
pub mod mount;
#[cfg(domain = "network")]
pub mod network;
#[cfg(domain = "obsidian")]
pub mod obsidian;
#[cfg(domain = "openclaw")]
pub mod openclaw;
#[cfg(domain = "projects")]
pub mod projects;
#[cfg(domain = "proxmox")]
pub mod proxmox;
#[cfg(domain = "setup")]
pub mod setup;
#[cfg(domain = "ssh")]
pub mod ssh;
#[cfg(domain = "synology")]
pub mod synology;
#[cfg(domain = "worktree")]
pub mod worktree;
#[cfg(domain = "workspace")]
pub mod workspace;
